version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:10.18
    working_directory: /tmp/repo

commands:
  restore_yarn:
    description: 'Restores yarn cache'
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_yarn
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - package
  test:
    executor: node-executor
    steps:
      - checkout
      - restore_yarn
      - run: yarn lint
      - run: yarn test
      - run:
          name: Upload Coverage Results
          command: |
            bash <(curl -s https://codecov.io/bash) \
            -f ./coverage/lcov.info \
            -n "$CIRCLE_BUILD_NUM-$CIRCLE_BRANCH"
  release:
    executor: node-executor
    steps:
      - checkout
      - restore_yarn
      - attach_workspace:
          at: .
      - run:
          command: |
            cd package
            yarn release

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - build
